import { initialCommercialFollowUpForm } from "./commercialFollowUpForm";

export function getCommercialFollowUpSectionProps({
  commercial,
  savingOrderAction,
  selectedSalesBranchLabel,
}) {
  const {
    branchScopedCommercialFollowUps,
    canManageCommercialFollowUp,
    canManageNotifications,
    commercialAgendaGroups,
    commercialAutomationRules,
    commercialAutomationSettings,
    commercialAutomationSource,
    commercialClientTimeline,
    commercialFollowUpForm,
    commercialFollowUpHistoryRows,
    commercialFollowUpOrders,
    commercialFollowUpRows,
    commercialFollowUpSummary,
    commercialFunnelStages,
    commercialReminderCards,
    commercialSellerFilter,
    commercialSellerOptions,
    dueCommercialFollowUps,
    handleCommercialFollowUpStatus,
    handleCreateCommercialFollowUp,
    handleSendCommercialNotifications,
    loadingNotificationStatus,
    notificationStatus,
    pendingCommercialFollowUps,
    priorityByClient,
    priorityBySeller,
    saveCommercialAutomationSettings,
    savingCommercialAutomation,
    setCommercialFollowUpForm,
    setCommercialSellerFilter,
    startCommercialFollowUp,
    updateCommercialAutomationSetting,
  } = commercial;

  return {
    agendaProps: {
      canManageNotifications,
      commercialAgendaGroups,
      commercialAutomationRules,
      commercialAutomationSettings,
      commercialAutomationSource,
      commercialClientTimeline,
      commercialReminderCards,
      dueCommercialFollowUps,
      handleSendCommercialNotifications,
      loadingNotificationStatus,
      notificationStatus,
      saveCommercialAutomationSettings,
      savingCommercialAutomation,
      savingOrderAction,
      updateCommercialAutomationSetting,
    },
    formProps: {
      canManageCommercialFollowUp,
      form: commercialFollowUpForm,
      onCancel: () => setCommercialFollowUpForm(initialCommercialFollowUpForm),
      onSubmit: handleCreateCommercialFollowUp,
      saving: savingOrderAction === "commercial-follow-up",
      setForm: setCommercialFollowUpForm,
    },
    headerProps: {
      commercialFollowUpRows,
      commercialFunnelStages,
      commercialSellerFilter,
      commercialSellerOptions,
      setCommercialSellerFilter,
    },
    historyProps: {
      branchScopedCommercialFollowUps,
      canManageCommercialFollowUp,
      commercialFollowUpHistoryRows,
      dueCommercialFollowUps,
      handleCommercialFollowUpStatus,
      pendingCommercialFollowUps,
      savingOrderAction,
    },
    kanbanProps: {
      canManageCommercialFollowUp,
      commercialFunnelStages,
      startCommercialFollowUp,
    },
    ordersTableProps: {
      canManageCommercialFollowUp,
      commercialFollowUpOrders,
      startCommercialFollowUp,
    },
    priorityProps: {
      priorityByClient,
      priorityBySeller,
      setCommercialSellerFilter,
    },
    sellerSummaryProps: {
      commercialFollowUpSummary,
      commercialSellerFilter,
      selectedSalesBranchLabel,
      setCommercialSellerFilter,
    },
  };
}
