export function getPointOfSaleCatalogProps({
  cartActions,
  caixa,
  cashMode,
  clientSearch,
  clientSearchRef,
  deliveryAddress,
  deliveryNote,
  deliveryType,
  discount,
  discountAmount,
  discountMode,
  paymentMethod,
  priority,
  productSearch,
  productSearchRef,
  quoteConditions,
  quoteValidity,
  selectedClienteId,
  setters,
  view,
}) {
  return {
    activeProducts: view.activeProducts,
    addProduct: cartActions.addProduct,
    addProductFromSearch: cartActions.addProductFromSearch,
    caixa,
    cashMode,
    clientSearch,
    clientSearchRef,
    deliveryAddress,
    deliveryNote,
    deliveryType,
    discount,
    discountAmount,
    discountMode,
    filteredClientes: view.filteredClientes,
    filteredProducts: view.filteredProducts,
    paymentMethod,
    priority,
    productSearch,
    productSearchRef,
    quoteConditions,
    quoteValidity,
    selectedClienteId,
    setClientSearch: setters.setClientSearch,
    setDeliveryAddress: setters.setDeliveryAddress,
    setDeliveryNote: setters.setDeliveryNote,
    setDeliveryType: setters.setDeliveryType,
    setDiscount: setters.setDiscount,
    setDiscountAmount: setters.setDiscountAmount,
    setDiscountMode: setters.setDiscountMode,
    setPaymentMethod: setters.setPaymentMethod,
    setPriority: setters.setPriority,
    setProductSearch: setters.setProductSearch,
    setQuoteConditions: setters.setQuoteConditions,
    setQuoteValidity: setters.setQuoteValidity,
    setSelectedClienteId: setters.setSelectedClienteId,
  };
}

export function getPointOfSaleCheckoutProps({
  cartActions,
  cashMode,
  draftControls,
  lastSale,
  message,
  mixedPayments,
  paymentInstallments,
  paymentMethod,
  proposalActions,
  receivedAmount,
  receivedAmountRef,
  saving,
  selectedClienteId,
  session,
  setters,
  view,
}) {
  return {
    cart: cartActions.cart,
    cashMode,
    cashReceiptDetail: view.cashReceiptDetail,
    cashReceiptReady: view.cashReceiptReady,
    change: view.change,
    changeQuantity: cartActions.changeQuantity,
    descontoValor: view.descontoValor,
    handleExportProposalCsv: proposalActions.handleExportProposalCsv,
    handlePrintProposal: proposalActions.handlePrintProposal,
    handleSaveQuote: proposalActions.handleSaveQuote,
    isMixedPayment: view.isMixedPayment,
    isPayOnDelivery: view.isPayOnDelivery,
    lastSale,
    message,
    mixedPaymentDifference: view.mixedPaymentDifference,
    mixedPayments,
    mixedPaymentTotal: view.mixedPaymentTotal,
    paymentInstallments,
    paymentMethod,
    paymentOptions: view.paymentOptions,
    receivedAmount,
    receivedAmountRef,
    removeProduct: cartActions.removeProduct,
    resetSaleDraft: draftControls.resetSaleDraft,
    saving,
    selectedCliente: view.selectedCliente,
    selectedClienteId,
    session,
    setMixedPayments: setters.setMixedPayments,
    setPaymentInstallments: setters.setPaymentInstallments,
    setPaymentMethod: setters.setPaymentMethod,
    setQuantity: cartActions.setQuantity,
    setQuickReceivedAmount: draftControls.setQuickReceivedAmount,
    setReceivedAmount: setters.setReceivedAmount,
    subtotal: view.subtotal,
    total: view.total,
  };
}
