export function getPointOfSaleDraftControlProps({
  cartActions,
  cashMode,
  proposalActions,
  refs,
  state,
  view,
}) {
  return {
    cart: cartActions.cart,
    cashMode,
    clientSearchRef: refs.clientSearchRef,
    formRef: refs.formRef,
    handleSaveQuote: proposalActions.handleSaveQuote,
    paymentOptions: view.paymentOptions,
    productSearchRef: refs.productSearchRef,
    receivedAmountRef: refs.receivedAmountRef,
    saving: state.saving,
    selectedCliente: view.selectedCliente,
    setCart: cartActions.setCart,
    setClientSearch: state.setClientSearch,
    setDeliveryAddress: state.setDeliveryAddress,
    setDeliveryNote: state.setDeliveryNote,
    setDeliveryType: state.setDeliveryType,
    setDiscount: state.setDiscount,
    setDiscountAmount: state.setDiscountAmount,
    setDiscountMode: state.setDiscountMode,
    setLastSale: state.setLastSale,
    setMessage: state.setMessage,
    setMixedPayments: state.setMixedPayments,
    setPaymentInstallments: state.setPaymentInstallments,
    setPaymentMethod: state.setPaymentMethod,
    setProductSearch: state.setProductSearch,
    setQuoteConditions: state.setQuoteConditions,
    setQuoteValidity: state.setQuoteValidity,
    setReceivedAmount: state.setReceivedAmount,
  };
}
