export function getPointOfSaleProposalActionProps({
  cartActions,
  onSaleCreated,
  session,
  state,
  view,
}) {
  return {
    buildProposal: view.buildProposal,
    cart: cartActions.cart,
    deliveryAddress: state.deliveryAddress,
    deliveryNote: state.deliveryNote,
    deliveryType: state.deliveryType,
    discountPayload: view.discountPayload,
    onSaleCreated,
    paymentInstallments: state.paymentInstallments,
    paymentMethod: state.paymentMethod,
    priority: state.priority,
    proposalBranchLabel: view.proposalBranchLabel,
    proposalNumber: view.proposalNumber,
    proposalRows: view.proposalRows,
    quoteConditions: state.quoteConditions,
    quoteValidity: state.quoteValidity,
    selectedCliente: view.selectedCliente,
    selectedClienteId: state.selectedClienteId,
    session,
    setMessage: state.setMessage,
    setSaving: state.setSaving,
    total: view.total,
  };
}

export function getPointOfSaleSubmissionProps({
  caixa,
  canOperateCash,
  cartActions,
  cashMode,
  onSaleCreated,
  session,
  state,
  view,
}) {
  return {
    caixa,
    canOperateCash,
    cart: cartActions.cart,
    cashMode,
    change: view.change,
    deliveryAddress: state.deliveryAddress,
    deliveryNote: state.deliveryNote,
    deliveryType: state.deliveryType,
    descontoValor: view.descontoValor,
    discountPayload: view.discountPayload,
    isMixedPayment: view.isMixedPayment,
    isPayOnDelivery: view.isPayOnDelivery,
    mixedPaymentDifference: view.mixedPaymentDifference,
    mixedPayments: state.mixedPayments,
    onSaleCreated,
    paymentInstallments: state.paymentInstallments,
    paymentMethod: state.paymentMethod,
    priority: state.priority,
    received: view.received,
    selectedCliente: view.selectedCliente,
    selectedClienteId: state.selectedClienteId,
    session,
    setCart: cartActions.setCart,
    setClientSearch: state.setClientSearch,
    setDeliveryAddress: state.setDeliveryAddress,
    setDeliveryNote: state.setDeliveryNote,
    setDeliveryType: state.setDeliveryType,
    setDiscount: state.setDiscount,
    setDiscountAmount: state.setDiscountAmount,
    setDiscountMode: state.setDiscountMode,
    setLastSale: state.setLastSale,
    setMessage: state.setMessage,
    setMixedPayments: state.setMixedPayments,
    setPaymentInstallments: state.setPaymentInstallments,
    setProductSearch: state.setProductSearch,
    setQuoteConditions: state.setQuoteConditions,
    setQuoteValidity: state.setQuoteValidity,
    setReceivedAmount: state.setReceivedAmount,
    setSaving: state.setSaving,
    setSelectedClienteId: state.setSelectedClienteId,
    subtotal: view.subtotal,
    total: view.total,
  };
}
