export const ROLES = Object.freeze({
  MASTER: "MASTER",
  ADMIN: "ADMIN",
  GERENTE: "GERENTE",
  VENDEDOR: "VENDEDOR",
  OPERADOR_CAIXA: "OPERADOR_CAIXA",
  ESTOQUISTA: "ESTOQUISTA",
  FINANCEIRO: "FINANCEIRO",
});

export const PRIVILEGED_ROLES = Object.freeze([ROLES.MASTER, ROLES.ADMIN]);
