export const statusToneByValue = {
  ORCAMENTO: "neutral",
  ABERTA: "warning",
  ABERTO: "warning",
  PENDENTE: "warning",
  AGUARDANDO: "warning",
  AGUARDANDO_HOMOLOGACAO: "warning",
  INATIVA: "warning",
  INATIVO: "warning",
  VENCENDO: "warning",
  ATRASADO: "danger",
  VENCIDO: "danger",
  SEPARACAO: "processing",
  SEPARADO: "processing",
  PLANEJADA: "neutral",
  EM_ANDAMENTO: "processing",
  EM_ANALISE: "processing",
  EM_EXECUCAO: "processing",
  EM_PROCESSAMENTO: "processing",
  XML_VALIDADO: "processing",
  EM_SEPARACAO: "processing",
  PRONTO_ENVIO: "processing",
  RECEBIDO: "warning",
  EM_ROTA: "processing",
  CONTINGENCIA: "warning",
  PAGO: "success",
  PAGA: "success",
  QUITADO: "success",
  QUITADA: "success",
  BAIXADO: "success",
  BAIXADA: "success",
  ATIVA: "success",
  ATIVO: "success",
  PRONTA: "success",
  PRONTO: "success",
  ONLINE: "success",
  COM_DADOS: "success",
  AUTORIZADO: "success",
  AUTORIZADA: "success",
  APROVADA: "success",
  APROVADO: "success",
  ENTREGUE: "success",
  FINALIZADA: "success",
  FINALIZADO: "success",
  CONCLUIDO: "success",
  CONCLUIDA: "success",
  FATURADA: "success",
  FATURADO: "success",
  PACOTE_REAL_PRONTO: "success",
  HOMOLOGADO: "success",
  CANCELADO: "danger",
  CANCELADA: "danger",
  INDISPONIVEL: "danger",
  BLOQUEADO: "danger",
  BLOQ: "danger",
  RECUSADO: "danger",
  ESTORNADO: "danger",
  REJEITADO: "danger",
  REJEITADA: "danger",
  INUTILIZADO: "danger",
  INUTILIZADA: "danger",
  EXPIRADO: "danger",
  EXPIRADA: "danger",
  ERRO: "danger",
  FALHA: "danger",
};

export const statusLabelByValue = {
  ORCAMENTO: "Orcamento",
  ABERTA: "Aberta",
  ABERTO: "Aberto",
  PENDENTE: "Pendente",
  AGUARDANDO: "Aguardando",
  AGUARDANDO_HOMOLOGACAO: "Aguardando homologação",
  INATIVA: "Inativa",
  INATIVO: "Inativo",
  VENCENDO: "Vencendo",
  ATRASADO: "Atrasado",
  VENCIDO: "Vencido",
  SEPARACAO: "Separação",
  SEPARADO: "Separado",
  PLANEJADA: "Planejada",
  EM_ANDAMENTO: "Em andamento",
  EM_ANALISE: "Em analise",
  EM_EXECUCAO: "Em execução",
  EM_PROCESSAMENTO: "Em processamento",
  XML_VALIDADO: "XML validado",
  EM_SEPARACAO: "Em separação",
  PRONTO_ENVIO: "Pronto envio",
  RECEBIDO: "Recebido",
  EM_ROTA: "Em rota",
  CONTINGENCIA: "Contingencia",
  PAGO: "Pago",
  PAGA: "Paga",
  QUITADO: "Quitado",
  QUITADA: "Quitada",
  BAIXADO: "Baixado",
  BAIXADA: "Baixada",
  ATIVA: "Ativa",
  ATIVO: "Ativo",
  PRONTA: "Pronta",
  PRONTO: "Pronto",
  ONLINE: "Online",
  COM_DADOS: "Com dados",
  AUTORIZADO: "Autorizado",
  AUTORIZADA: "Autorizada",
  APROVADA: "Aprovada",
  APROVADO: "Aprovado",
  ENTREGUE: "Entregue",
  FINALIZADA: "Finalizada",
  FINALIZADO: "Finalizado",
  CONCLUIDO: "Concluido",
  CONCLUIDA: "Concluída",
  FATURADA: "Faturada",
  FATURADO: "Faturado",
  PACOTE_REAL_PRONTO: "Pacote real pronto",
  HOMOLOGADO: "Homologado",
  CANCELADO: "Cancelado",
  CANCELADA: "Cancelada",
  INDISPONIVEL: "Indisponivel",
  BLOQUEADO: "Bloqueado",
  BLOQ: "Bloq.",
  RECUSADO: "Recusado",
  ESTORNADO: "Estornado",
  REJEITADO: "Rejeitado",
  REJEITADA: "Rejeitada",
  INUTILIZADO: "Inutilizado",
  INUTILIZADA: "Inutilizada",
  EXPIRADO: "Expirado",
  EXPIRADA: "Expirada",
  ERRO: "Erro",
  FALHA: "Falha",
};

export const orderStatusOptions = [
  { value: "todos", label: "Todos" },
  { value: "FINALIZADA", label: "Finalizadas" },
  { value: "ORCAMENTO", label: "Orcamentos" },
  { value: "PENDENTE", label: "Pendentes" },
  { value: "SEPARACAO", label: "Separação" },
  { value: "SEPARADO", label: "Separados" },
  { value: "RECEBIDO", label: "Recebidos" },
  { value: "CONCLUIDO", label: "Concluidos" },
];

export const orderPeriodOptions = [
  { value: "todos", label: "Tudo", days: null },
  { value: "7", label: "7 dias", days: 7 },
  { value: "30", label: "30 dias", days: 30 },
];
