import { FinanceReconciliationAlert } from "./FinanceReconciliationAlert";
import { FinanceReconciliationSection } from "./FinanceReconciliationSection";

export function FinanceReconciliationDashboardSection({
  allVisibleOrphansSelected,
  applyOrphanHistoryPreset,
  caixasComDivergencia,
  caixaFinanceiroDiff,
  cashDivergenceRef,
  criticalInconsistencyCount,
  currentOrphanHistoryPage,
  filteredOrphanCancellationEvents,
  financeiroSemPedido,
  focusInconsistencyCard,
  focusInconsistencyPanel,
  getPedidoItemSummary,
  handleCancelOrphanOrder,
  handleCancelOrphanOrders,
  handleReconciliationAction,
  handleToggleOrphanSelection,
  handleToggleVisibleOrphans,
  inconsistencyCards,
  inconsistencyPanelRef,
  inconsistencyRows,
  isAdmin,
  mediumInconsistencyCount,
  orphanCancellationRows,
  orphanHistoryFilter,
  orphanHistoryRef,
  orphanHistoryTotalPages,
  orphanlessRevenueRef,
  orphanOrdersRef,
  orphanPreview,
  orphanReportRows,
  pagedOrphanCancellationEvents,
  pedidosSemItens,
  reconciliationActionPlan,
  reconciliationLabel,
  reconciliationRows,
  reconciliationScore,
  reconciliationTone,
  salesWithoutFinanceRef,
  saving,
  sectionSession,
  selectedOrphanIds,
  setOrphanHistoryFilter,
  setOrphanHistoryPage,
  vendasCaixaDiff,
  vendasSemFinanceiro,
}) {
  return (
    <>
      <FinanceReconciliationAlert
        criticalInconsistencyCount={criticalInconsistencyCount}
        focusInconsistencyPanel={focusInconsistencyPanel}
        mediumInconsistencyCount={mediumInconsistencyCount}
      />

      <FinanceReconciliationSection
        allVisibleOrphansSelected={allVisibleOrphansSelected}
        applyOrphanHistoryPreset={applyOrphanHistoryPreset}
        caixasComDivergencia={caixasComDivergencia}
        caixaFinanceiroDiff={caixaFinanceiroDiff}
        cashDivergenceRef={cashDivergenceRef}
        currentOrphanHistoryPage={currentOrphanHistoryPage}
        filteredOrphanCancellationEvents={filteredOrphanCancellationEvents}
        financeiroSemPedido={financeiroSemPedido}
        focusInconsistencyCard={focusInconsistencyCard}
        getPedidoItemSummary={getPedidoItemSummary}
        handleCancelOrphanOrder={handleCancelOrphanOrder}
        handleCancelOrphanOrders={handleCancelOrphanOrders}
        handleReconciliationAction={handleReconciliationAction}
        handleToggleOrphanSelection={handleToggleOrphanSelection}
        handleToggleVisibleOrphans={handleToggleVisibleOrphans}
        inconsistencyCards={inconsistencyCards}
        inconsistencyPanelRef={inconsistencyPanelRef}
        inconsistencyRows={inconsistencyRows}
        isAdmin={isAdmin}
        orphanCancellationRows={orphanCancellationRows}
        orphanHistoryFilter={orphanHistoryFilter}
        orphanHistoryRef={orphanHistoryRef}
        orphanHistoryTotalPages={orphanHistoryTotalPages}
        orphanlessRevenueRef={orphanlessRevenueRef}
        orphanOrdersRef={orphanOrdersRef}
        orphanPreview={orphanPreview}
        orphanReportRows={orphanReportRows}
        pagedOrphanCancellationEvents={pagedOrphanCancellationEvents}
        pedidosSemItens={pedidosSemItens}
        reconciliationActionPlan={reconciliationActionPlan}
        reconciliationLabel={reconciliationLabel}
        reconciliationRows={reconciliationRows}
        reconciliationScore={reconciliationScore}
        reconciliationTone={reconciliationTone}
        salesWithoutFinanceRef={salesWithoutFinanceRef}
        saving={saving}
        sectionSession={sectionSession}
        selectedOrphanIds={selectedOrphanIds}
        setOrphanHistoryFilter={setOrphanHistoryFilter}
        setOrphanHistoryPage={setOrphanHistoryPage}
        vendasCaixaDiff={vendasCaixaDiff}
        vendasSemFinanceiro={vendasSemFinanceiro}
      />
    </>
  );
}
