import { FinanceOperationsSection } from "./FinanceOperationsSection";
import { FinanceReconciliationDashboardSection } from "./FinanceReconciliationDashboardSection";

export function FinanceReconciliationOperationsSection({
  actions,
  dashboard,
  orphanActions,
  orphanHistoryControls,
  saving,
  session,
  state,
}) {
  return (
    <>
      <FinanceReconciliationDashboardSection
        allVisibleOrphansSelected={orphanActions.allVisibleOrphansSelected}
        applyOrphanHistoryPreset={orphanHistoryControls.applyOrphanHistoryPreset}
        caixasComDivergencia={dashboard.caixasComDivergencia}
        caixaFinanceiroDiff={dashboard.caixaFinanceiroDiff}
        cashDivergenceRef={dashboard.cashDivergenceRef}
        criticalInconsistencyCount={dashboard.criticalInconsistencyCount}
        currentOrphanHistoryPage={dashboard.currentOrphanHistoryPage}
        filteredOrphanCancellationEvents={dashboard.filteredOrphanCancellationEvents}
        financeiroSemPedido={dashboard.financeiroSemPedido}
        focusInconsistencyCard={actions.focusInconsistencyCard}
        focusInconsistencyPanel={actions.focusInconsistencyPanel}
        getPedidoItemSummary={dashboard.getPedidoItemSummary}
        handleCancelOrphanOrder={orphanActions.handleCancelOrphanOrder}
        handleCancelOrphanOrders={orphanActions.handleCancelOrphanOrders}
        handleReconciliationAction={actions.handleReconciliationAction}
        handleToggleOrphanSelection={orphanActions.handleToggleOrphanSelection}
        handleToggleVisibleOrphans={orphanActions.handleToggleVisibleOrphans}
        inconsistencyCards={dashboard.inconsistencyCards}
        inconsistencyPanelRef={dashboard.inconsistencyPanelRef}
        inconsistencyRows={dashboard.inconsistencyRows}
        isAdmin={dashboard.isAdmin}
        mediumInconsistencyCount={dashboard.mediumInconsistencyCount}
        orphanCancellationRows={dashboard.orphanCancellationRows}
        orphanHistoryFilter={orphanHistoryControls.orphanHistoryFilter}
        orphanHistoryRef={dashboard.orphanHistoryRef}
        orphanHistoryTotalPages={dashboard.orphanHistoryTotalPages}
        orphanlessRevenueRef={dashboard.orphanlessRevenueRef}
        orphanOrdersRef={dashboard.orphanOrdersRef}
        orphanPreview={dashboard.orphanPreview}
        orphanReportRows={dashboard.orphanReportRows}
        pagedOrphanCancellationEvents={dashboard.pagedOrphanCancellationEvents}
        pedidosSemItens={dashboard.pedidosSemItens}
        reconciliationActionPlan={dashboard.reconciliationActionPlan}
        reconciliationLabel={dashboard.reconciliationLabel}
        reconciliationRows={dashboard.reconciliationRows}
        reconciliationScore={dashboard.reconciliationScore}
        reconciliationTone={dashboard.reconciliationTone}
        salesWithoutFinanceRef={dashboard.salesWithoutFinanceRef}
        saving={saving}
        sectionSession={session}
        selectedOrphanIds={orphanActions.selectedOrphanIds}
        setOrphanHistoryFilter={orphanHistoryControls.setOrphanHistoryFilter}
        setOrphanHistoryPage={orphanHistoryControls.setOrphanHistoryPage}
        vendasCaixaDiff={dashboard.vendasCaixaDiff}
        vendasSemFinanceiro={dashboard.vendasSemFinanceiro}
      />

      <FinanceOperationsSection
        branchScopedMovimentacoes={dashboard.branchScopedMovimentacoes}
        canMutateFinance={dashboard.canMutateFinance}
        canReverseFinance={dashboard.canReverseFinance}
        copyChargeText={actions.copyChargeText}
        currentFinancePage={dashboard.currentFinancePage}
        filiais={dashboard.filiais}
        financeCategoryOptions={dashboard.financeCategoryOptions}
        financeFilter={state.financeFilter}
        editingFinanceId={state.editingFinanceId}
        financeFilterLabel={dashboard.financeFilterLabel}
        financeMovementRows={dashboard.financeMovementRows}
        financePageSize={dashboard.financePageSize}
        financeTotalPages={dashboard.financeTotalPages}
        filteredMovimentacoes={dashboard.filteredMovimentacoes}
        form={state.form}
        getFinanceItemSummary={dashboard.getFinanceItemSummaryForMovement}
        handleEditFinanceItem={actions.handleEditFinanceItem}
        handleGenerateCharge={actions.handleGenerateCharge}
        handleStatusAction={actions.handleStatusAction}
        handleSubmit={actions.handleSubmit}
        message={state.message}
        pagedMovimentacoes={dashboard.pagedMovimentacoes}
        saving={saving}
        selectedCharge={state.selectedCharge}
        selectedFinanceBranchLabel={dashboard.selectedFinanceBranchLabel}
        session={session}
        setFinancePage={state.setFinancePage}
        setEditingFinanceId={state.setEditingFinanceId}
        setForm={state.setForm}
        setMessage={state.setMessage}
        setSelectedCharge={state.setSelectedCharge}
        setShowFinanceForm={state.setShowFinanceForm}
        showFinanceForm={state.showFinanceForm}
      />
    </>
  );
}
